[package]
name = "skybooking"
version = "1.0.0"
description = "Air Ticket Booking System"

[dependencies]
"php/php" = "^8.2"

[[module]]
name = "skybooking"
source = "."
abi = "wasi"

[fs]
"/app" = "."
"/storage" = "storage"

[command]
name = "skybooking"
module = "skybooking"
runner = "https://webc.org/runner/wasi"

[[command.annotations.wasi.env]]
DOCUMENT_ROOT = "/app"

[command.annotations.wasi]
main-args = ["-S", "0.0.0.0:8080", "-t", "/app"]
