[package]
name = "skybooking"
version = "1.0.0"
description = "Air Ticket Booking System"

[dependencies]
"php/php" = "^8.2"

[fs]
"/app" = "."

[[command]]
name = "run"
module = "php/php:php"
runner = "wasi"

[command.annotations.wasi]
env = ["DOCUMENT_ROOT=/app"]
main-args = ["-S", "0.0.0.0:8080", "-t", "/app"]

[command.annotations.wasi.atom]
volumes = [
  { host = ".", guest = "/app" },
  { name = "storage", guest = "/app/storage" }
]
